version: '3.9'

services:
   mongo_db:
     container_name: database-container
     image: mongo:latest
     restart: always
     ports:
             - 2717:27017
     volumes:
       - mongodb:/data/db
     networks:
       - app-network

    #Node js app
   node_app:
     build: .
     ports:
      - 5010:6000
      - 5000:3000
     volumes:
      - type: bind
        source: ./home/ubuntu/inventory-app
        target: /usr/src/app
     environment:
            DB_URI: mongodb://mongo_db:27017
     networks:
      - app-network
     depends_on:
      - mongo_db
     
     
networks:
    app-network:
        driver: bridge

volumes:
  mongodb:
