version: '3.9'

services:
   mongo_db:
     container_name: database-container
     image: mongo:latest
     restart: always
     ports:
<<<<<<< HEAD
       - 2717:27017
     volumes:
       - mongodb:/data/db
     networks:
       - app-network
=======
             - 2717:27017
     volumes:
       - mongodb:/data/db
>>>>>>> master

    #Node js app
   node_app:
     build: .
     ports:
<<<<<<< HEAD
      - 5000:5000
      - 3000:3000
     volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/views/node_modules
     environment:
            DB_URI: mongodb://mongo_db:27017
     networks:
      - app-network
     depends_on:
      - mongo_db
     
     
networks:
    app-network:
        driver: bridge
=======
      - 5010:5000
      - 5000:3000
     environment:
            PORT: 5000
            DB_URI: mongodb://mongo_db:27017
>>>>>>> master

volumes:
  mongodb:
