version: '3.9'

services:
   mongo_db:
     container_name: database-container
     image: mongo:latest
     restart: always
     ports:
             - 2717:27017
     volumes:
       - mongodb:/data/db

    #Node js app
   node_app:
     build: .
     ports:
      - 5010:5000
      - 5000:3000
     environment:
            DB_URI: mongodb://mongo_db:27017

volumes:
  mongodb:
